In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')
import pandas as pd

In [2]:
b=np.array(([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]]))

In [6]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [7]:
print(b)
print(b.T)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
[[ 0 10 20 30 40]
 [ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]]


In [8]:
b.reshape(2,-1)

array([[ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21],
       [22, 23, 30, 31, 32, 33, 40, 41, 42, 43]])

In [9]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [17]:
a = np.array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [18]:
s = a[:,1:3]

In [19]:
s[:]=10

In [20]:
s

array([[10, 10],
       [10, 10],
       [10, 10]])

In [21]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [24]:
a = np.arange(12).reshape(3,4)
i = np.array([[0, 1],[1, 2]])
j = np.array([[2, 1], [3, 3]])
a
i
j
a[i,j]

array([[ 2,  5],
       [ 7, 11]])

In [25]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
i

array([[0, 1],
       [1, 2]])

In [27]:
j

array([[2, 1],
       [3, 3]])

In [28]:
a[i,j]

array([[ 2,  5],
       [ 7, 11]])

In [29]:
def bubble_sort(arr):
    '''Implements the bubble sort algorithm. However, upon on each swap,
    append the new list as the next "row" in a list containing all the
    swaps. The original list should be the first row in the list detailing
    the swaps.

    Parameters
    ----------
    arr: list

    Returns
    -------
    list of lists

    >>>bubble_sort([7, 4, 2, 5])
    [[7, 4, 2, 5],
     [4, 7, 2, 5],
     [4, 2, 7, 5],
     [4, 2, 5, 7],
     [2, 4, 5, 7]]

    '''
    lst1=[arr]
    for i in range(len(arr)-1):
        for j in range(i+1,len(arr)):
            if arr[i]>arr[j]:
                arr[i], arr[j] = arr[j], arr[i]
            lst1.append(arr)
                
    return lst1 

In [49]:
print(bubble_sort([7, 4, 2, 5]))

[2, 4, 5, 7]


In [48]:
def bubble_sort(a):
    
    for j in range(len(a)):
   
        swapped = False
        i = 0
        while i<len(a)-1:
        
            if a[i]>a[i+1]:
            #swapping
                a[i],a[i+1] = a[i+1],a[i]
            #Changing the value of swapped
                swapped = True
            i = i+1
    #if swapped is false then the list is sorted
    #we can stop the loop
        if swapped == False:
            break
            
    return a